// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjN1XhEjfck4bXuL29_HxeEDil6MWVRsY',
    appId: '1:526669991624:web:9ec66c3e9d9862cbce1ffd',
    messagingSenderId: '526669991624',
    projectId: 'petshop-6fcd2',
    authDomain: 'petshop-6fcd2.firebaseapp.com',
    storageBucket: 'petshop-6fcd2.appspot.com',
    measurementId: 'G-5RDVV6TZBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA_704aQgO_aRftAMjhY6z_qc3CFjbLAo',
    appId: '1:526669991624:android:4873fc029b381d1fce1ffd',
    messagingSenderId: '526669991624',
    projectId: 'petshop-6fcd2',
    storageBucket: 'petshop-6fcd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBswqHeygumMFYc3Y3D6V2ivuedjH9fnrY',
    appId: '1:526669991624:ios:a30c3255eaa0ac54ce1ffd',
    messagingSenderId: '526669991624',
    projectId: 'petshop-6fcd2',
    storageBucket: 'petshop-6fcd2.appspot.com',
    iosBundleId: 'com.example.petshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBswqHeygumMFYc3Y3D6V2ivuedjH9fnrY',
    appId: '1:526669991624:ios:a30c3255eaa0ac54ce1ffd',
    messagingSenderId: '526669991624',
    projectId: 'petshop-6fcd2',
    storageBucket: 'petshop-6fcd2.appspot.com',
    iosBundleId: 'com.example.petshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjN1XhEjfck4bXuL29_HxeEDil6MWVRsY',
    appId: '1:526669991624:web:b3d165b44b436231ce1ffd',
    messagingSenderId: '526669991624',
    projectId: 'petshop-6fcd2',
    authDomain: 'petshop-6fcd2.firebaseapp.com',
    storageBucket: 'petshop-6fcd2.appspot.com',
    measurementId: 'G-J11H595DLW',
  );

}